-- EpinAnonymOS guest startup.
--
-- hyprland.lua require()s custom/execs.lua after hyprland/execs.lua, and hl.on() is ADDITIVE --
-- the host's own startup block still runs.  Everything it launches (quickshell, kitty, hypridle,
-- easyeffects, gnome-keyring, cliphist/wl-paste, dbus-update-activation-environment) is absent
-- from this image, so each of those exec_cmd calls fails harmlessly (the boot log shows them as
-- "[exec] not found: ..."); they are left in place so hyprland/execs.lua stays a verbatim copy
-- of the host's file.
--
-- NOTHING is started from here any more.  Both of this guest's desktop clients are spawned by
-- the kernel instead, from spawnWaylandClients() in kernel_main.d:
--
--     [bar] wl-layer-bar
--     [dm]  wl-domain-manager      <- moved here 2026-09-03
--     [g11] wl-cairo-demo
--
-- Why the kernel and not this file.  hl.exec_cmd DOES work in this guest -- the domain manager
-- really did come up as tid 6 and spoke Wayland -- but it fires on the hyprland.start event,
-- which is before the compositor has settled, and it logs nothing.  That made "is the domain
-- manager actually running?" answerable only by grepping serial.log trace lines for a task name.
-- The kernel path waits for the /run/user/1000/wayland-0 listener plus GUI_CLIENT_SETTLE_TICKS
-- and prints "[dm] wl-domain-manager launched as task N", so a single grep answers it.
--
-- That autostart is gated on g_guiClientAutostartEnabled = initIsHyprland, so it applies to
-- Hyprland only; Weston keeps taking its list from /desktop.conf.
--
-- To add another client at boot, put it next to the others in spawnWaylandClients() rather than
-- here -- keeping one mechanism means one place to look when something does not come up.
