timeout: 0
verbose: yes
serial: yes
textmode: no
interface_branding: EpinAnonymOS

/EpinAnonymOS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: display.width=1280 display.height=800 display.scale=1 display.refresh=60 display.force_mode=0 gui.autostart=cairo
    resolution: 1280x800x32
    module_path: boot():/busybox
    module_path: boot():/test-drm
    module_path: boot():/compositor
    module_path: boot():/hello-gui
    module_path: boot():/wl-probe
    module_path: boot():/display-info
    module_path: boot():/wl-shm-demo
    module_path: boot():/wl-term
    module_path: boot():/-sh
    module_path: boot():/display.conf

    module_path: boot():/wl-cairo-demo

    module_path: boot():/wl-files

    module_path: boot():/gtk-hello

    module_path: boot():/Hyprland
    module_path: boot():/ld-musl-x86_64.so.1
    module_path: boot():/kms_swrast_dri.so
    module_path: boot():/swrast_dri.so

    module_path: boot():/xkb.blob

    module_path: boot():/fonts.blob
    module_path: boot():/icons.blob
    module_path: boot():/cursors.blob
    module_path: boot():/wallpapers.blob
    module_path: boot():/themes.blob
