timeout: 0
verbose: yes
serial: yes
textmode: no
interface_branding: EpinAnonymOS

/EpinAnonymOS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: display.width=1280 display.height=800 display.scale=1 display.refresh=60 display.force_mode=0 gui.autostart=cairo
    resolution: 1280x800x32
    module_path: boot():/busybox
    module_path: boot():/test-drm
    module_path: boot():/compositor
    module_path: boot():/hello-gui
    module_path: boot():/wl-probe
    module_path: boot():/display-info
    module_path: boot():/wl-shm-demo
    module_path: boot():/wl-term
    module_path: boot():/-sh
    module_path: boot():/hos-sh
    module_path: boot():/zsh
    module_path: boot():/idle
    module_path: boot():/store-app
    module_path: boot():/display.conf
    module_path: boot():/attr.so
    module_path: boot():/cap.so
    module_path: boot():/clone.so
    module_path: boot():/compctl.so
    module_path: boot():/complete.so
    module_path: boot():/complist.so
    module_path: boot():/computil.so
    module_path: boot():/curses.so
    module_path: boot():/datetime.so
    module_path: boot():/deltochar.so
    module_path: boot():/example.so
    module_path: boot():/files.so
    module_path: boot():/langinfo.so
    module_path: boot():/mapfile.so
    module_path: boot():/mathfunc.so
    module_path: boot():/nearcolor.so
    module_path: boot():/newuser.so
    module_path: boot():/param_private.so
    module_path: boot():/parameter.so
    module_path: boot():/regex.so
    module_path: boot():/rlimits.so
    module_path: boot():/sched.so
    module_path: boot():/socket.so
    module_path: boot():/stat.so
    module_path: boot():/system.so
    module_path: boot():/tcp.so
    module_path: boot():/termcap.so
    module_path: boot():/terminfo.so
    module_path: boot():/watch.so
    module_path: boot():/zftp.so
    module_path: boot():/zle.so
    module_path: boot():/zleparameter.so
    module_path: boot():/zprof.so
    module_path: boot():/zpty.so
    module_path: boot():/zselect.so
    module_path: boot():/zutil.so

    module_path: boot():/wl-cairo-demo

    module_path: boot():/wl-files

    module_path: boot():/gtk-hello

    module_path: boot():/Hyprland
    module_path: boot():/ld-musl-x86_64.so.1
    module_path: boot():/kms_swrast_dri.so
    module_path: boot():/swrast_dri.so

    module_path: boot():/xkb.blob

    module_path: boot():/fonts.blob
    module_path: boot():/icons.blob
    module_path: boot():/cursors.blob
    module_path: boot():/wallpapers.blob
    module_path: boot():/themes.blob

    module_path: boot():/weston
    module_path: boot():/ld-musl-x86_64.so.1
    module_path: boot():/libexec_weston.so.0
    module_path: boot():/libweston-14.so.0
    module_path: boot():/drm-backend.so
    module_path: boot():/desktop-shell.so
    module_path: boot():/weston-desktop-shell
    module_path: boot():/weston-keyboard
    module_path: boot():/wl-domain-manager
    module_path: boot():/desktop.conf
    module_path: boot():/weston-terminal
