timeout: 0
verbose: no
quiet: yes
serial: yes
textmode: no
interface_branding: EpinAnonymOS

/EpinAnonymOS
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: display.width=1280 display.height=800 display.scale=1 display.refresh=60 display.force_mode=0
    resolution: 1280x800x32
    module_path: boot():/busybox
    module_path: boot():/mke2fs
    module_path: boot():/unsquashfs
    module_path: boot():/bsdtar
    module_path: boot():/gpgv
    module_path: boot():/test-drm
    module_path: boot():/drm-gpu-test
    module_path: boot():/compositor
    module_path: boot():/hello-gui
    module_path: boot():/wl-probe
    module_path: boot():/display-info
    module_path: boot():/wl-shm-demo
    module_path: boot():/wl-term
    module_path: boot():/hos-wifi
    module_path: boot():/-sh
    module_path: boot():/hos-sh
    module_path: boot():/zsh
    module_path: boot():/idle
    module_path: boot():/store-app
    module_path: boot():/display.conf
