"""A signed manifest of every static asset.

WHY THIS IS NOT OPTIONAL
------------------------
Dynamic responses are signed on their way out of Flask. Static files are not:
nginx serves `/static/` directly and never reaches the application. That left
every stylesheet and every script unsigned — including verify-origin.js, the
script whose entire job is to detect tampering.

That is not a loose end, it is a bypass. Modify the verifier and it reports
"content verified" for anything; the reader sees a green result while being
served whatever the gateway likes. The protection was covering the pages and
leaving the guard unprotected.

So the assets get a manifest: SHA-256 per file, a Merkle tree over them, and one
Ed25519 signature on the root. One signature covers ten thousand files, and any
individual file proves membership with a path of log(n) hashes.

BUILT FROM DISK, NOT FROM A BUILD STEP
--------------------------------------
Generated by walking the directory that is actually being served, lazily, and
cached. A separate build step can disagree with what shipped — the classic
failure is a manifest describing the files someone meant to deploy. Reading the
bytes nginx will hand out makes that impossible.

The cost is one pass over static/ per process, on first request. Static files do
not change under a running pod: a new build is a new image.
"""

import os
import threading
import time

from shared import app

from services.content_signing import (
    merkle_proof, merkle_root, public_key_b64, sha256_hex, sign_manifest,
)

# Files nobody fetches, or that would bloat the manifest without protecting
# anything a reader executes. Everything a browser RUNS or RENDERS is included;
# these are not that.
SKIP_SUFFIXES = (".map", ".md", ".txt", ".log", ".pyc")
SKIP_DIRS = {"__pycache__", ".git", "node_modules"}

# A ceiling, so a directory that unexpectedly contains a media dump cannot turn
# every first request into a multi-minute hash of the disk.
MAX_FILES = 5000
MAX_BYTES_PER_FILE = 16 * 1024 * 1024

_lock = threading.Lock()
_cached = None


def _static_root():
    return app.static_folder or os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "static")


def _walk(root):
    """Every servable asset, in a STABLE order.

    Sorted, because the Merkle root depends on leaf order: two processes that
    walked the same directory in different orders would sign different roots for
    identical content, and the client would report a forgery that never happened.
    """
    found = []
    for base, dirs, files in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
        for name in sorted(files):
            if name.endswith(SKIP_SUFFIXES) or name.startswith("."):
                continue
            absolute = os.path.join(base, name)
            try:
                if os.path.getsize(absolute) > MAX_BYTES_PER_FILE:
                    continue
            except OSError:
                continue
            found.append((os.path.relpath(absolute, root).replace(os.sep, "/"), absolute))
            if len(found) >= MAX_FILES:
                app.logger.warning(
                    "static manifest stopped at %d files; the rest are UNSIGNED",
                    MAX_FILES)
                return found
    return found


def _hash_file(path):
    import hashlib

    digest = hashlib.sha256()
    try:
        with open(path, "rb") as handle:
            for chunk in iter(lambda: handle.read(65536), b""):
                digest.update(chunk)
    except OSError:
        return None
    return digest.hexdigest()


def build():
    """Hash every asset, build the tree, sign the root."""
    root = _static_root()
    entries = []
    for relative, absolute in _walk(root):
        digest = _hash_file(absolute)
        if digest is not None:
            entries.append({"path": relative, "sha256": digest})

    leaves = [e["sha256"] for e in entries]
    tree_root = merkle_root(leaves)
    released_at = int(time.time())
    signature = sign_manifest(tree_root, released_at, len(entries))

    return {
        "version": 1,
        "algorithm": "sha256",
        "merkle_root": tree_root,
        "released_at": released_at,
        "count": len(entries),
        "public_key": public_key_b64(),
        "signature": signature,
        "signed": bool(signature),
        "files": {e["path"]: e["sha256"] for e in entries},
        # Kept so a client can rebuild the tree and check a proof itself rather
        # than taking our word for the ordering.
        "order": [e["path"] for e in entries],
    }


def manifest():
    """The cached manifest, built on first use."""
    global _cached
    if _cached is not None:
        return _cached
    with _lock:
        if _cached is None:
            started = time.time()
            _cached = build()
            app.logger.info("static manifest: %d file(s), root %s, signed=%s, %.2fs",
                            _cached["count"], _cached["merkle_root"][:16],
                            _cached["signed"], time.time() - started)
    return _cached


def proof_for(path):
    """The Merkle path proving one asset belongs to the signed root."""
    data = manifest()
    order = data.get("order") or []
    try:
        index = order.index(path)
    except ValueError:
        return None
    leaves = [data["files"][p] for p in order]
    return {"path": path, "sha256": data["files"][path],
            "proof": merkle_proof(leaves, index),
            "merkle_root": data["merkle_root"]}


def integrity_for(relative_path):
    """A Subresource Integrity value for one asset, e.g. "sha384-...".

    Separate from the manifest on purpose. SRI is enforced by the BROWSER before
    the script runs, so it protects the verifier from being modified without
    depending on the verifier — which is the circularity the manifest alone
    cannot escape: a tampered verifier will happily declare itself valid.
    """
    import base64
    import hashlib

    absolute = os.path.join(_static_root(), relative_path.replace("/", os.sep))
    try:
        with open(absolute, "rb") as handle:
            digest = hashlib.sha384(handle.read()).digest()
    except OSError:
        return None
    return "sha384-" + base64.b64encode(digest).decode("ascii")


_integrity_cache = {}


def cached_integrity(relative_path):
    if relative_path not in _integrity_cache:
        _integrity_cache[relative_path] = integrity_for(relative_path)
    return _integrity_cache[relative_path]
