import hashlib
from urllib.parse import quote

from flask import has_request_context, request, url_for

from shared import app


_DEFAULT_PIECE_LENGTH = 256 * 1024
_MIN_PIECE_LENGTH = 64 * 1024
_SMALL_FILE_THRESHOLD = 1024 * 1024


def torrent_display_name(media_id, media_ext):
    return "media-%s.%s" % (media_id, media_ext)


def torrent_piece_length(file_length):
    if int(file_length or 0) <= _SMALL_FILE_THRESHOLD:
        return _MIN_PIECE_LENGTH
    return _DEFAULT_PIECE_LENGTH


def _bencode(value):
    if isinstance(value, bool):
        value = int(value)
    if isinstance(value, int):
        return ("i%de" % value).encode("ascii")
    if isinstance(value, bytes):
        return ("%d:" % len(value)).encode("ascii") + value
    if isinstance(value, str):
        encoded = value.encode("utf-8")
        return ("%d:" % len(encoded)).encode("ascii") + encoded
    if isinstance(value, (list, tuple)):
        return b"l" + b"".join(_bencode(item) for item in value) + b"e"
    if isinstance(value, dict):
        encoded_items = []
        for key, item in value.items():
            if isinstance(key, bytes):
                encoded_key = key
            else:
                encoded_key = str(key).encode("utf-8")
            encoded_items.append((encoded_key, item))
        encoded_items.sort(key=lambda pair: pair[0])
        return b"d" + b"".join(_bencode(key) + _bencode(item) for key, item in encoded_items) + b"e"
    raise TypeError("Unsupported bencode value %r" % (value,))


def torrent_info_dict(attachment_bytes, media_id, media_ext, piece_length=None):
    attachment_bytes = bytes(attachment_bytes or b"")
    chosen_piece_length = int(piece_length or torrent_piece_length(len(attachment_bytes)))
    pieces = []
    for offset in range(0, len(attachment_bytes), chosen_piece_length):
        piece_bytes = attachment_bytes[offset:offset + chosen_piece_length]
        pieces.append(hashlib.sha1(piece_bytes).digest())
    return {
        "name": torrent_display_name(media_id, media_ext),
        "piece length": chosen_piece_length,
        "pieces": b"".join(pieces),
        "length": len(attachment_bytes),
    }


def torrent_info_hash_for_bytes(attachment_bytes, media_id, media_ext, piece_length=None):
    info = torrent_info_dict(
        attachment_bytes,
        media_id=media_id,
        media_ext=media_ext,
        piece_length=piece_length,
    )
    info_bytes = _bencode(info)
    return hashlib.sha1(info_bytes).hexdigest(), int(info["piece length"])


def torrent_file_bytes(
    attachment_bytes,
    media_id,
    media_ext,
    announce_urls=None,
    piece_length=None,
):
    info = torrent_info_dict(
        attachment_bytes,
        media_id=media_id,
        media_ext=media_ext,
        piece_length=piece_length,
    )
    announce_urls = [url for url in (announce_urls or []) if url]
    payload = {
        "creation date": 0,
        "created by": "Maniwani",
        "comment": "Generated by Maniwani for browser torrent delivery",
        "info": info,
    }
    if announce_urls:
        payload["announce"] = announce_urls[0]
        payload["announce-list"] = [[url] for url in announce_urls]
    return _bencode(payload)


def magnet_url(
    info_hash,
    display_name=None,
    announce_urls=None,
    torrent_url=None,
):
    if not info_hash:
        return None
    magnet_parts = [
        "xt=urn:btih:%s" % info_hash,
    ]
    if display_name:
        magnet_parts.append("dn=%s" % quote(display_name))
    if torrent_url:
        magnet_parts.append("xs=%s" % quote(torrent_url, safe=":/?&=%"))
    for announce_url in [url for url in (announce_urls or []) if url]:
        magnet_parts.append("tr=%s" % quote(announce_url, safe=":/?&=%"))
    return "magnet:?%s" % "&".join(magnet_parts)


def _host_parts():
    # URLs returned to a browser must follow the host that browser used. A
    # deployment-level host is still needed for background jobs, but letting a
    # default such as ``localhost`` override an active request produces magnets
    # that try to connect every remote viewer to their own machine.
    configured_host = (app.config.get("TORRENT_PUBLIC_HOST") or "").strip()
    normalized_host = configured_host.lower()
    configured_host_is_local = (
        normalized_host in {"localhost", "127.0.0.1", "::1", "[::1]"}
        or normalized_host.startswith("localhost:")
        or normalized_host.startswith("127.0.0.1:")
        or normalized_host.startswith("[::1]:")
    )
    if has_request_context():
        request_host = (request.host or "").strip()
        if request_host and (
            not configured_host or configured_host_is_local
        ):
            return request_host, request.is_secure
    if configured_host:
        return configured_host, bool(app.config.get("TORRENT_PUBLIC_SECURE", True))
    if has_request_context():
        return request.host, request.is_secure
    scheme = (app.config.get("PREFERRED_URL_SCHEME") or "https").lower()
    host = (app.config.get("SERVER_NAME") or "localhost").strip()
    return host, scheme == "https"


def public_tracker_urls():
    host, secure = _host_parts()
    http_scheme = "https" if secure else "http"
    ws_scheme = "wss" if secure else "ws"
    return [
        "%s://%s/tracker/announce" % (ws_scheme, host),
        "%s://%s/tracker/announce" % (http_scheme, host),
    ]


# Build an absolute URL from the configured/public host without needing a
# request context or Flask's SERVER_NAME. url_for(_external=True) raises
# "Unable to build URLs outside an active request without SERVER_NAME" when
# called from the background aggregator-sync greenlet, which used to abort every
# imported-media save; this resolves the host the same way the tracker URLs do.
def absolute_upload_url(path):
    host, secure = _host_parts()
    scheme = "https" if secure else "http"
    if not path.startswith("/"):
        path = "/" + path
    return "%s://%s%s" % (scheme, host, path)


def public_magnet_url(media_id, media_ext, info_hash, include_torrent_url=False):
    if not info_hash:
        return None
    torrent_url = None
    if include_torrent_url:
        torrent_url = absolute_upload_url("/upload/%d/torrent" % media_id)
    return magnet_url(
        info_hash,
        display_name=torrent_display_name(media_id, media_ext),
        announce_urls=public_tracker_urls(),
        torrent_url=torrent_url,
    )


def turn_ice_servers():
    turn_host = (app.config.get("TORRENT_TURN_HOST") or "").strip()
    if not turn_host:
        host, _secure = _host_parts()
        turn_host = host.split(":", 1)[0]
    stun_port = int(app.config.get("TORRENT_TURN_PORT") or 3478)
    tls_port = int(app.config.get("TORRENT_TURNS_PORT") or 5349)
    username = (app.config.get("TORRENT_TURN_USERNAME") or "").strip()
    credential = (app.config.get("TORRENT_TURN_PASSWORD") or "").strip()
    servers = [
        {"urls": ["stun:%s:%d" % (turn_host, stun_port)]},
    ]
    turn_urls = [
        "turn:%s:%d?transport=udp" % (turn_host, stun_port),
        "turn:%s:%d?transport=tcp" % (turn_host, stun_port),
        "turns:%s:%d?transport=tcp" % (turn_host, tls_port),
    ]
    if username and credential:
        servers.append({
            "urls": turn_urls,
            "username": username,
            "credential": credential,
        })
    else:
        servers.append({"urls": turn_urls})
    return servers


def media_torrent_payload(media_id, media_ext, info_hash, piece_length=None):
    if not info_hash:
        return None
    announce_urls = public_tracker_urls()
    display_name = torrent_display_name(media_id, media_ext)
    torrent_url = absolute_upload_url("/upload/%d/torrent" % media_id)
    return {
        "media_id": media_id,
        "display_name": display_name,
        "info_hash": info_hash,
        "piece_length": int(piece_length or 0) or None,
        "announce_urls": announce_urls,
        "torrent_url": torrent_url,
        "magnet_url": public_magnet_url(media_id, media_ext, info_hash, include_torrent_url=False),
        "magnet_source": "generated",
    }


def resolved_media_torrent_payload(media):
    payload = media_torrent_payload(
        getattr(media, "id", None),
        getattr(media, "ext", None),
        getattr(media, "torrent_info_hash", None),
        piece_length=getattr(media, "torrent_piece_length", None),
    )
    if payload is None:
        return None, False

    from model.ImageMagnet import media_supports_image_magnets, sync_image_magnet_url

    payload["magnet_url"], changed = sync_image_magnet_url(media, payload["magnet_url"])
    if media_supports_image_magnets(media):
        payload["magnet_source"] = "db"
    payload["mimetype"] = getattr(media, "mimetype", None)
    return payload, changed
