#!/usr/bin/env python3
"""Rebuild Darling's Linux-side programs as static musl executables for anonymOS.

Darling has exactly four ELF programs -- the `darling` launcher, `darlingserver`, `mldr` (the Mach-O
loader) and `darling-coredump`; everything else it installs is Mach-O and independent of the host
libc.  Its CMake build compiles those four with the host clang against glibc, which anonymOS (a musl
userland) cannot run.  This replays each target's own compile and link commands, as recorded in the
finished Darling build's ninja graph, with the repo's musl toolchain (deps/musl/install musl-clang /
musl-clang++, libc++), writing objects and binaries into <build>/../build-musl and linking -static.

Usage: darling-musl-host.py <darling build dir> [target ...]
"""
import os, shlex, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MUSL_BIN = os.path.join(ROOT, "deps/musl/install/bin")
TARGETS = {
    "darling": "src/startup/darling",
    "darlingserver": "src/external/darlingserver/darlingserver",
    "mldr": "src/startup/mldr/mldr",
    "darling-coredump": "src/tools/darling-coredump/darling-coredump",
}
COMPILERS = {"/usr/bin/clang": "musl-clang", "/usr/bin/clang++": "musl-clang++"}
# musl has no getcontext/makecontext/setcontext (darlingserver's micro-threads use them): libucontext,
# built static by scripts/build-darling.sh into deps/darling/build-tools.
UCONTEXT = os.path.join(ROOT, "deps/darling/build-tools/src/libucontext-libucontext-1.3.2")


def target_commands(build, target):
    out = subprocess.run(["ninja", "-C", build, "-t", "commands", target],
                         check=True, capture_output=True, text=True).stdout
    return [l for l in out.splitlines() if l.strip()]


def strip_wrapper(cmd):
    # CMake link lines look like ": && /usr/bin/clang ... && :"
    cmd = cmd.strip()
    if cmd.startswith(": &&"):
        cmd = cmd[4:]
    if cmd.endswith("&& :"):
        cmd = cmd[:-4]
    return cmd.strip()


# glibc spellings Darling's sources lean on that musl does not provide; force-included in every compile.
GLIBC_COMPAT = """/* generated by scripts/darling-musl-host.py */
#pragma once
#include <stdint.h>
typedef int8_t __int8_t;   typedef uint8_t __uint8_t;
typedef int16_t __int16_t; typedef uint16_t __uint16_t;
typedef int32_t __int32_t; typedef uint32_t __uint32_t;
typedef int64_t __int64_t; typedef uint64_t __uint64_t;
#ifndef ACCESSPERMS
# define ACCESSPERMS 0777   /* glibc <sys/stat.h> */
#endif
#ifndef ALLPERMS
# define ALLPERMS 07777
#endif
#ifndef DEFFILEMODE
# define DEFFILEMODE 0666
#endif
"""


# Headers glibc ships and musl deliberately does not; searched after musl's own (-idirafter).
COMPAT_INCLUDES = {
    "sys/cdefs.h": """/* generated by scripts/darling-musl-host.py: the glibc <sys/cdefs.h> subset Darling uses */
#pragma once
#ifdef __cplusplus
# define __BEGIN_DECLS extern "C" {
# define __END_DECLS }
# define __THROW throw()
#else
# define __BEGIN_DECLS
# define __END_DECLS
# define __THROW
#endif
#define __P(args) args
#define __CONCAT(x, y) x ## y
#define __STRING(x) #x
#ifndef __restrict
# define __restrict restrict
#endif
#define __inline inline
#define __attribute_deprecated__ __attribute__((__deprecated__))
#define __wur __attribute__((__warn_unused_result__))
#define __nonnull(params) __attribute__((__nonnull__ params))
""",
}


# glibc entry points referenced by the objects (XNU's fortified string macros in duct-tape, libc++abi's
# thread_local destructor hook); compiled once and linked into every binary.
GLIBC_COMPAT_C = r"""/* generated by scripts/darling-musl-host.py */
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
void *__memcpy_chk(void *d, const void *s, size_t n, size_t dn) { if (n > dn) abort(); return memcpy(d, s, n); }
void *__memmove_chk(void *d, const void *s, size_t n, size_t dn) { if (n > dn) abort(); return memmove(d, s, n); }
void *__memset_chk(void *d, int c, size_t n, size_t dn) { if (n > dn) abort(); return memset(d, c, n); }
char *__strcpy_chk(char *d, const char *s, size_t dn) { size_t n = strlen(s) + 1; if (n > dn) abort(); return memcpy(d, s, n); }
char *__strncpy_chk(char *d, const char *s, size_t n, size_t dn) { if (n > dn) abort(); return strncpy(d, s, n); }
char *__strcat_chk(char *d, const char *s, size_t dn) { if (strlen(d) + strlen(s) + 1 > dn) abort(); return strcat(d, s); }
/* thread_local destructors: run at thread exit through a pthread key (not for the main thread at exit()). */
struct tl_dtor { void (*fn)(void *); void *obj; struct tl_dtor *next; };
static pthread_key_t tl_key;
static pthread_once_t tl_once = PTHREAD_ONCE_INIT;
static void tl_run(void *p) { for (struct tl_dtor *d = p, *n; d; d = n) { n = d->next; d->fn(d->obj); free(d); } }
static void tl_make(void) { pthread_key_create(&tl_key, tl_run); }
int __cxa_thread_atexit_impl(void (*fn)(void *), void *obj, void *dso) {
    (void)dso;
    pthread_once(&tl_once, tl_make);
    struct tl_dtor *d = malloc(sizeof *d);
    if (!d) return -1;
    d->fn = fn; d->obj = obj; d->next = pthread_getspecific(tl_key);
    pthread_setspecific(tl_key, d);
    return 0;
}
"""


def compat_object(out_dir):
    src = os.path.join(out_dir, "glibc-compat.c")
    obj = os.path.join(out_dir, "glibc-compat.o")
    write_if_changed(src, GLIBC_COMPAT_C)
    subprocess.run([os.path.join(MUSL_BIN, "musl-clang"), "-O2", "-c", src, "-o", obj], check=True)
    return obj


def write_if_changed(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if not os.path.exists(path) or open(path).read() != text:
        open(path, "w").write(text)


def compat_header(out_dir):
    path = os.path.join(out_dir, "glibc-compat.h")
    write_if_changed(path, GLIBC_COMPAT)
    for rel, text in COMPAT_INCLUDES.items():
        write_if_changed(os.path.join(out_dir, "compat-include", rel), text)
    return path


def rewrite(tokens, out_dir, link):
    t = list(tokens)
    t[0] = os.path.join(MUSL_BIN, COMPILERS[t[0]])
    if not link:
        t[1:1] = ["-include", compat_header(out_dir), "-idirafter", os.path.join(out_dir, "compat-include")]
    res, i = [], 0
    while i < len(t):
        tok = t[i]
        if tok in ("-o", "-MF", "-MT") and i + 1 < len(t):
            path = t[i + 1]
            if tok != "-MT" and not os.path.isabs(path):
                path = os.path.join(out_dir, path)
                os.makedirs(os.path.dirname(path), exist_ok=True)
            res += [tok, path]
            i += 2
            continue
        if link and (tok.endswith(".o") or tok.endswith(".a")) and not os.path.isabs(tok):
            tok = os.path.join(out_dir, tok)
        if tok in ("-ggdb", "-g"):       # keep the static binaries small
            i += 1
            continue
        res.append(tok)
        i += 1
    if link:
        res.insert(1, "-static")
        res += [compat_object(out_dir),
                os.path.join(UCONTEXT, "libucontext_posix.a"), os.path.join(UCONTEXT, "libucontext.a")]
    return res


def replay_archives(cmds, build, out_dir):
    """Rebuild the target's static libraries from the musl objects ("llvm-ar qc LIB.a objs...")."""
    for c in cmds:
        for seg in c.split("&&"):
            tok = shlex.split(seg)
            if len(tok) < 3 or not tok[0].endswith("llvm-ar") or tok[1] != "qc":
                continue
            lib = os.path.join(out_dir, tok[2])
            objs = [os.path.join(out_dir, o) for o in tok[3:]]
            os.makedirs(os.path.dirname(lib), exist_ok=True)
            if os.path.exists(lib):
                os.remove(lib)
            subprocess.run([tok[0], "qc", lib] + objs, cwd=build, check=True)
            subprocess.run([tok[0].replace("llvm-ar", "llvm-ranlib"), lib], cwd=build, check=True)


def build_target(build, name):
    target = TARGETS[name]
    out_dir = os.path.join(os.path.dirname(os.path.abspath(build)), "build-musl")
    cmds = [strip_wrapper(c) for c in target_commands(build, target)]
    compiles = [c for c in cmds if " -c " in c and "apple-darwin" not in c
                and shlex.split(c)[0] in COMPILERS]
    links = [c for c in cmds if (" -o " + target + " ") in c or c.endswith(" -o " + target)
             or (" -o " + target + " ") in c + " "]
    if not links:
        sys.exit(f"{name}: no link command for {target}")
    for c in compiles:
        r = subprocess.run(rewrite(shlex.split(c), out_dir, False), cwd=build,
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stderr)
            sys.exit(f"{name}: compile failed: {c[:200]}")
    replay_archives(cmds, build, out_dir)
    r = subprocess.run(rewrite(shlex.split(links[-1]), out_dir, True), cwd=build,
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stderr)
        sys.exit(f"{name}: link failed")
    print(f"{name}: {len(compiles)} objects -> {os.path.join(out_dir, target)}")


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    build = os.path.abspath(sys.argv[1])
    for name in (sys.argv[2:] or ["mldr", "darling", "darlingserver"]):
        build_target(build, name)


if __name__ == "__main__":
    main()
