#!/usr/bin/env python3
"""Stage generated GUI assets for the guest asset pipeline.

The source tree for boot assets lives under build/assets and is packed later by
scripts/pack-assets.py.  This script keeps G10 assets reproducible: it creates a
small original icon/theme/background set and, when available, vendors the libre
DMZ cursor theme into the generated Epin cursor theme.
"""
from __future__ import annotations

import argparse
import shutil
import struct
import zlib
from pathlib import Path


GENERATED_LICENSE = """Epin generated GUI assets

Files generated by scripts/stage-gui-assets.py are dedicated to the public
domain under CC0-1.0, or may be used under the project license at your option.

Bundled DMZ cursor files, when present, retain their upstream license. See
LICENSE.DMZ-White.txt in the generated icon theme directory.
"""


def write_text(path: Path, data: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data, encoding="utf-8")


def write_png(path: Path, width: int, height: int, variant: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    rows = []
    for y in range(height):
        row = bytearray([0])
        for x in range(width):
            fx = x / max(1, width - 1)
            fy = y / max(1, height - 1)
            if variant == 1:
                r = int(30 + 42 * fx + 16 * fy)
                g = int(44 + 96 * fy)
                b = int(58 + 110 * (1.0 - fx))
            elif variant == 2:
                r = int(38 + 100 * fy)
                g = int(46 + 72 * (1.0 - fx))
                b = int(72 + 90 * fx)
            else:
                r = int(32 + 92 * fx)
                g = int(48 + 84 * (1.0 - abs(fx - fy)))
                b = int(64 + 96 * fy)
            row.extend((r, g, b))
        rows.append(bytes(row))

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    data = b"\x89PNG\r\n\x1a\n"
    data += chunk(b"IHDR", ihdr)
    data += chunk(b"IDAT", zlib.compress(b"".join(rows), level=9))
    data += chunk(b"IEND", b"")
    path.write_bytes(data)


def svg_icon(kind: str) -> str:
    base = {
        # GTK's last-resort icon.  gtkiconhelper.c:495 does
        #   g_assert(error == NULL)
        # after looking up "image-missing", so when ANY icon lookup fails and image-missing is
        # absent too, GTK does not degrade -- it aborts the process.  That is what killed every
        # GTK client here: gtk_image_new_from_icon_name("terminal", ...) missed, the fallback
        # missed as well, and the app raised SIGABRT before creating its first surface.
        "image-missing": """
  <rect x="14" y="24" width="100" height="80" rx="10" fill="#1E293B" stroke="#64748B" stroke-width="6"/>
  <path d="M30 88l24-30 16 20 12-14 16 24z" fill="#475569"/>
  <circle cx="46" cy="46" r="9" fill="#94A3B8"/>
  <path d="M24 34l80 60" stroke="#EF4444" stroke-width="8" stroke-linecap="round"/>
""",
        "terminal": """
  <rect x="8" y="10" width="112" height="88" rx="18" fill="#111827"/>
  <rect x="8" y="10" width="112" height="24" rx="18" fill="#334155"/>
  <path d="M28 53l18 14-18 14" fill="none" stroke="#E2E8F0" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M56 82h34" fill="none" stroke="#38BDF8" stroke-width="8" stroke-linecap="round"/>
""",
        "file-manager": """
  <path d="M14 30h38l10 12h52v52a12 12 0 0 1-12 12H26a12 12 0 0 1-12-12z" fill="#0F766E"/>
  <path d="M14 40h100v52a12 12 0 0 1-12 12H26a12 12 0 0 1-12-12z" fill="#5EEAD4"/>
  <path d="M28 60h72" stroke="#134E4A" stroke-width="7" stroke-linecap="round"/>
""",
        "settings": """
  <circle cx="64" cy="64" r="22" fill="#F8FAFC"/>
  <path d="M64 16l10 14 17-3 5 17 16 8-8 16 8 16-16 8-5 17-17-3-10 14-10-14-17 3-5-17-16-8 8-16-8-16 16-8 5-17 17 3z" fill="#475569"/>
  <circle cx="64" cy="64" r="18" fill="#F8FAFC"/>
  <circle cx="64" cy="64" r="9" fill="#0EA5E9"/>
""",
        "system-monitor": """
  <rect x="14" y="18" width="100" height="84" rx="16" fill="#1E293B"/>
  <path d="M26 76h14l10-26 15 38 12-24h25" fill="none" stroke="#22C55E" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M28 36h72" stroke="#94A3B8" stroke-width="7" stroke-linecap="round"/>
""",
        "folder": """
  <path d="M12 34h38l9 12h57v48a12 12 0 0 1-12 12H24a12 12 0 0 1-12-12z" fill="#0369A1"/>
  <path d="M12 46h104v48a12 12 0 0 1-12 12H24a12 12 0 0 1-12-12z" fill="#7DD3FC"/>
""",
        "text-x-generic": """
  <path d="M30 14h48l20 20v80H30z" fill="#F8FAFC"/>
  <path d="M78 14v24h24" fill="#CBD5E1"/>
  <path d="M44 54h40M44 70h40M44 86h28" stroke="#334155" stroke-width="7" stroke-linecap="round"/>
""",
    }[kind]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
  <rect width="128" height="128" rx="28" fill="#E5E7EB"/>
{base}</svg>
"""


def stage_icons(root: Path) -> None:
    theme = root / "icons" / "Epin"
    if theme.exists():
        shutil.rmtree(theme)
    (theme / "scalable" / "apps").mkdir(parents=True, exist_ok=True)
    (theme / "scalable" / "places").mkdir(parents=True, exist_ok=True)
    (theme / "scalable" / "mimetypes").mkdir(parents=True, exist_ok=True)
    write_text(theme / "LICENSE.txt", GENERATED_LICENSE)
    write_text(
        theme / "index.theme",
        """[Icon Theme]
Name=Epin
Comment=Generated Epin desktop icon theme
Inherits=hicolor
Directories=scalable/apps,scalable/places,scalable/mimetypes

[scalable/apps]
Size=128
Type=Scalable
MinSize=16
MaxSize=256
Context=Applications

[scalable/places]
Size=128
Type=Scalable
MinSize=16
MaxSize=256
Context=Places

[scalable/mimetypes]
Size=128
Type=Scalable
MinSize=16
MaxSize=256
Context=MimeTypes
""",
    )
    for name in ("terminal", "file-manager", "settings", "system-monitor"):
        write_text(theme / "scalable" / "apps" / f"{name}.svg", svg_icon(name))
    write_text(theme / "scalable" / "places" / "folder.svg", svg_icon("folder"))
    write_text(theme / "scalable" / "mimetypes" / "text-x-generic.svg", svg_icon("text-x-generic"))

    default = root / "icons" / "default"
    if default.exists():
        shutil.rmtree(default)
    write_text(default / "index.theme", "[Icon Theme]\nInherits=Epin\n")
    write_text(default / "cursor.theme", "[Icon Theme]\nInherits=Epin\n")

    # hicolor is the theme every other theme inherits from, and it shipped EMPTY --
    # "Directories=" with nothing behind it.  So when a lookup missed in Epin, the fallback chain
    # ended nowhere, GTK then looked for "image-missing", found nothing there either, and
    # gtkiconhelper.c aborted the process.  Give hicolor the fallback icon GTK requires.
    hicolor = root / "icons" / "hicolor"
    # PNG, not SVG.  librsvg here is a STUB (deps/hyprland-hos/Makefile.deps builds
    # librsvg-stub), so gdk-pixbuf cannot decode an SVG at all -- which is why writing
    # image-missing.svg changed nothing and GTK still aborted with the icon "not present".
    # gdk-pixbuf handles PNG natively, so the fallback has to be a PNG to actually load.
    # Several fixed sizes because GTK picks by requested size; GTK_ICON_SIZE_DIALOG is 48.
    sizes = (16, 22, 24, 32, 48, 64, 128)
    for i, sz in enumerate(sizes):
        write_png(hicolor / f"{sz}x{sz}" / "status" / "image-missing.png", sz, sz, i)
    dirs = ",".join(f"{sz}x{sz}/status" for sz in sizes)
    body = "[Icon Theme]\nName=hicolor\nDirectories=" + dirs + "\n"
    for sz in sizes:
        body += f"\n[{sz}x{sz}/status]\nSize={sz}\nType=Fixed\nContext=Status\n"
    write_text(hicolor / "index.theme", body)


def stage_cursors(root: Path, cursor_src: Path | None, cursor_license: Path | None) -> None:
    icon_theme = root / "icons" / "Epin"
    cursors = icon_theme / "cursors"
    if cursors.exists():
        shutil.rmtree(cursors)
    cursors.mkdir(parents=True, exist_ok=True)
    default_cursors = root / "icons" / "default" / "cursors"
    if default_cursors.exists():
        shutil.rmtree(default_cursors)

    if cursor_src and (cursor_src / "cursors").is_dir():
        for src in sorted((cursor_src / "cursors").iterdir()):
            if src.is_file():
                shutil.copy2(src, cursors / src.name)
        if cursor_license and cursor_license.is_file():
            shutil.copy2(cursor_license, icon_theme / "LICENSE.DMZ-White.txt")
        else:
            write_text(
                icon_theme / "LICENSE.DMZ-White.txt",
                "DMZ-White cursor files are libre cursor theme assets. Install "
                "dmz-cursor-theme documentation for full upstream license text.\n",
            )

    write_text(icon_theme / "cursor.theme", "[Icon Theme]\nInherits=Epin\n")
    write_text(root / "cursors" / "Epin" / "cursor.theme", "[Icon Theme]\nInherits=Epin\n")


def stage_backgrounds(root: Path) -> None:
    backgrounds = root / "backgrounds" / "epin"
    if backgrounds.exists():
        shutil.rmtree(backgrounds)
    backgrounds.mkdir(parents=True, exist_ok=True)
    write_text(backgrounds / "LICENSE.txt", GENERATED_LICENSE)
    write_text(
        backgrounds / "wall0.svg",
        """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#102033"/>
      <stop offset="0.52" stop-color="#0F766E"/>
      <stop offset="1" stop-color="#7C3AED"/>
    </linearGradient>
  </defs>
  <rect width="1920" height="1080" fill="url(#g)"/>
  <path d="M0 812c300-120 560-92 824-12 302 92 610 160 1096-20v300H0z" fill="#E2E8F0" opacity="0.16"/>
  <path d="M0 920c352-76 570-34 860 8 326 48 646 56 1060-118v270H0z" fill="#0F172A" opacity="0.24"/>
</svg>
""",
    )

    hypr = root / "hypr"
    hypr.mkdir(parents=True, exist_ok=True)
    for idx in range(3):
        src = hypr / f"wall{idx}.png"
        if not src.exists():
            write_png(src, 320, 200, idx)
        if idx == 0:
            shutil.copy2(src, backgrounds / "wall0.png")


def stage_themes(root: Path) -> None:
    theme = root / "themes" / "Epin"
    if theme.exists():
        shutil.rmtree(theme)
    write_text(theme / "LICENSE.txt", GENERATED_LICENSE)
    write_text(
        theme / "index.theme",
        """[Desktop Entry]
Name=Epin
Type=X-GNOME-Metatheme
Comment=Generated Epin desktop theme

[X-GNOME-Metatheme]
GtkTheme=Epin
IconTheme=Epin
CursorTheme=Epin
ButtonLayout=close,minimize,maximize:
""",
    )
    settings = """[Settings]
gtk-theme-name=Epin
gtk-icon-theme-name=Epin
gtk-cursor-theme-name=Epin
gtk-font-name=Noto Sans 10
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-application-prefer-dark-theme=0
"""
    write_text(theme / "gtk-3.0" / "settings.ini", settings)
    write_text(theme / "gtk-4.0" / "settings.ini", settings)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("asset_root", type=Path)
    parser.add_argument("--cursor-src", type=Path)
    parser.add_argument("--cursor-license", type=Path)
    args = parser.parse_args()

    root = args.asset_root
    root.mkdir(parents=True, exist_ok=True)
    stage_icons(root)
    stage_cursors(root, args.cursor_src, args.cursor_license)
    stage_backgrounds(root)
    stage_themes(root)
    write_text(root / "hos" / "assets" / "README.txt", GENERATED_LICENSE)
    print(f"stage-gui-assets: staged generated GUI assets under {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
