// This file is auto-generated by tools/update_sh_metadata.py
module sh_metadata;

static if (!__traits(compiles, { size_t dummy; }))
{
    alias size_t = typeof(int.sizeof);
}

enum string shRepositoryPath = "/-sh";
enum string shBinaryName = "lfe-sh";
enum string shRevision = "a44ee38bfa8771f665d1a39590325a29b328d045";
enum size_t shSourceFileCount = 91u;
enum size_t shDocumentedCommandCount = 296u;
enum size_t shBinarySizeBytes = 5512688u;
