PROJECT_ROOT ?= $(abspath ../../../../..)
PROG_NAME=storage
PROG_HS_FILES=storage.hs Hos/Storage.hs Hos/Storage/Msg.hs
PROG_LIB_HS_FILES=Hos/Storage.hs Hos/Storage/Msg.hs
PROG_CFLAGS=
PROG_JHC_FLAGS=-pinit

include $(PROJECT_ROOT)/src/progs/build/build-prog.mk
include $(PROJECT_ROOT)/src/progs/build/build-prog-lib.mk
